world = {
    (0, 0): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (0, 1): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (0, 2): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (1, 0): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (1, 1): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (1, 2): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (2, 0): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (2, 1): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
    (2, 2): {
        "owner": None,
        (0, 0): None,
        (0, 1): None,
        (0, 2): None,
        (1, 0): None,
        (1, 1): None,
        (1, 2): None,
        (2, 0): None,
        (2, 1): None,
        (2, 2): None,
    },
}
